<?php

namespace Echyzen\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotCleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotCleRepository extends EntityRepository
{

}
