<?php

namespace Echyzen\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriqueRepository extends EntityRepository
{

	public function getRubriqueByAlph() {
		return $this->createQueryBuilder('r')->orderBy('r.nom')->getQuery()->getResult();
	}
}
