<?php

namespace Echyzen\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriqueRepository extends EntityRepository
{

	public function getRubriqueByAlph() {
		return $this->createQueryBuilder('r')->orderBy('r.nom')->getQuery()->getResult();
	}

	/**
	*	@return id & name of rubrique and count of news
	*	
	*/
	public function getRubriqueAndCountByAlph() {
		return $this->createQueryBuilder('r')
			->select('r.id', 'r.nom','COUNT(n.id) as co')
			->leftJoin('r.news', 'n')
			->groupBy('r.id')
			->where('n.id IS NOT NULL')
			->andWhere('n.publication = 1')
			->orderBy('r.nom')->getQuery()->getResult();
	}
}
