imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'EchyzenNewsBundle:Form:fields.html.twig'
            - 'EchyzenTestBundle:Form:number_field.html.twig'
            - 'EchyzenTestBundle:Form:lol.html.twig'

# Assetic Configuration
assetic:
    debug: "%kernel.debug%" 
    #false
    use_controller: false
    bundles:        [ EchyzenNewsBundle, EchyzenTestBundle, FMElfinderBundle ]
    java: 'C:\Program Files (x86)\Java\jre1.8.0_31\bin\java.exe'
    ruby: 'C:\Ruby193\bin\ruby.exe'
    sass: 'C:\Ruby193\bin\sass.bat'
    ruby: %ruby%
    filters:
        cssrewrite: ~
        sass:
            bin: %sass%
            apply_to: "\.scss$"
        compass:
            bin: %compass%
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    datetime_functions:
                        MONTH: Echyzen\NewsBundle\DQL\Month
                        YEAR: Echyzen\NewsBundle\DQL\Year

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver:     orm                            # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                           # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    Echyzen\UserBundle\Entity\User # La classe de l'entité User que nous utilisons

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: simple# other choices are tinymce or simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            compression: false # enable if you configured the uglifycss and uglifyjs2 assetic filters and want compression
            connector:
                debug: true # defaults to false
                roots:     # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: %kernel.root_dir%
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M

genemu_form:
    tinymce: ~
