echyzen_test:
    resource: "@EchyzenTestBundle/Resources/config/routing.yml"
    prefix:   /

#Mise en place du routing pour le routing Ajax
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

echyzen_admin:
    resource: "@EchyzenAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

#Mise en place du routing pour la connection
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#Mise en place du routing pour mes propres bundles
echyzen_index:
    resource: "@EchyzenIndexBundle/Resources/config/routing.yml"
    prefix:   /

echyzen_news:
    resource: "@EchyzenNewsBundle/Resources/config/routing.yml"
    prefix:   /

sdz_blog:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
