login:
    pattern:   /login
    defaults:  { _controller: EchyzenUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

echyzen_index:
    resource: "@EchyzenIndexBundle/Resources/config/routing.yml"
    prefix:   /

echyzen_news:
    resource: "@EchyzenNewsBundle/Resources/config/routing.yml"
    prefix:   /

sdz_blog:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /

