security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Echyzen\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_MODERATEUR:  ROLE_USER
        ROLE_ADMIN:       ROLE_MODERATEUR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #a effacer config de base inclu par defaut dans symfony avec un user mdp: userpass et un admin mdp: adminpass
        #in_memory:
        #   memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: /
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
