admin_news_index:
    pattern:  /
    defaults: { _controller: "EchyzenAdminBundle:News:index" }
admin_news_liste:
    pattern:  /liste_news
    defaults: { _controller: "EchyzenAdminBundle:News:liste" }
admin_news_create:
    pattern:  /create_news
    defaults: { _controller: "EchyzenAdminBundle:News:create" }