admin_news_index:
    pattern:  /
    defaults: { _controller: "EchyzenAdminBundle:News:index" }
admin_news_liste:
    pattern:  /liste_news
    defaults: { _controller: "EchyzenAdminBundle:News:liste" }
admin_news_create:
    pattern:  /create_news
    defaults: { _controller: "EchyzenAdminBundle:News:create" }
admin_news_edit:
    pattern:  /edit_news/{id}
    defaults: { _controller: "EchyzenAdminBundle:News:edit" }
    requirements:
        id:    \d+
admin_news_delete:
    pattern:  /delete_news/{id}
    defaults: { _controller: "EchyzenAdminBundle:News:delete" }
    requirements:
        id:    \d+