parameters:
#    echyzen_admin.example.class: Echyzen\AdminBundle\Example

services:
#    echyzen_admin.example:
#        class: %echyzen_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
