parameters:
    twitter_name: echyzenWebsite

services:
    echyzen_news.socialbar:
        class: Echyzen\NewsBundle\Services\SocialBar
        arguments: [%twitter_name%]
        tags:
            -  { name: twig.extension }
