parameters:
    twitter_name: echyzenWebsite
    bbcode_to_html : { gras : i, b : strong, }

services:
    echyzen_news.socialbar:
        class: Echyzen\NewsBundle\Services\SocialBar
        arguments: [%twitter_name%]
        tags:
            -  { name: twig.extension }
    echyzen_news.parse:
        class: Echyzen\NewsBundle\Services\Parse
        arguments: [%bbcode_to_html%]
        tags:
            -  { name: twig.extension }
    echyzen_news.textparse:
        class: Echyzen\NewsBundle\Form\TextParseType
        tags:
            - { name: form.type, alias: textparse }
