parameters:
#    echyzen_news.example.class: Echyzen\NewsBundle\Example

services:
#    echyzen_news.example:
#        class: %echyzen_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
