parameters:
#    echyzen_user.example.class: Echyzen\UserBundle\Example

services:
#    echyzen_user.example:
#        class: %echyzen_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
