parameters:
    echyzen_test.index_genre_delimiter: ':'
#    echyzen_test.example.class: Echyzen\TestBundle\Example
#    echyzen_test.example:
#        class: %echyzen_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
