parameters:
#    echyzen_test.example.class: Echyzen\TestBundle\Example

services:
#    echyzen_test.example:
#        class: %echyzen_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
