news:
    pattern:  /
    defaults: { _controller: "EchyzenNewsBundle:News:index" }

news_show:
    pattern:  /{id}/show
    defaults: { _controller: "EchyzenNewsBundle:News:show" }

#ajout par moi
news_by_rubrique:
    pattern:  /{id}/rubrique
    defaults: { _controller: "EchyzenNewsBundle:News:getByRubrique" }
    options:
        expose: true

news_create_commentaire:
    pattern: /create_commentaire/{id}
    defaults: { _controller: "EchyzenNewsBundle:News:createCommentaire" }
    options:
        expose: true